### ISSUE TITLE
Long url causes fixture written failure because of file name over the limit.

### ISSUE THREAD

**Issue by chenchaoyi** [TestArmada/drydock-scaffold#1]
Long url causes fixture written failure because of file name over the limit.

```
Unhandled rejection Error: ENAMETOOLONG: name too long, open 'fixtures/www.google.com%2Fxjs%2F_%2Fjs%2Fk%3Dxjs.s.en_US.r_s_X6Or2LQ.O%2Fm%3Dabd%2Csy59%2Csy58%2Csy57%2Csy60%2Casync%2Cerh%2Csy61%2Cfoot%2Cfpe%2Cidck%2Cifl%2Cipv6%2Clc%2Csy32%2Csy140%2Clu%2Cm%2Csf%2Csy35%2Csy41%2Csy101%2Csy201%2Csy36%2Csy42%2Csy39%2Csy127%2Csy93%2Csy202%2Csy89%2Csy139%2Csy133%2Csy135%2Csy203%2Csy243%2Csy208%2Csy250%2Csy244%2Csy204%2Csy257%2Csy270%2Csy40%2Csy110%2Cem7%2Cem8%2Cem6%2Cem4%2Csy271%2Cskp%2Cvm%2Fam%3DIEkRACCI-J0PAuHCMCakIhBhMQ%2Frt%3Dj%2Fd%3D0%2Ft%3Dzcms%2Frs%3DACT90oGgX5TwOefeS511ogxigKXTPXyxIA%20get-0.html'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1161:15)
    at writeFixture (/Users/cchen21/WEC/try/mock/node_modules/drydock-scaffold/lib/write-mocks.js:138:16)
    at /Users/cchen21/WEC/try/mock/node_modules/drydock-scaffold/lib/write-mocks.js:151:27
    at Array.map (native)
    at /Users/cchen21/WEC/try/mock/node_modules/drydock-scaffold/lib/write-mocks.js:150:64
    at Array.map (native)
    at writeMocks (/Users/cchen21/WEC/try/mock/node_modules/drydock-scaffold/lib/write-mocks.js:147:41)
    at /Users/cchen21/WEC/try/mock/node_modules/drydock-scaffold/lib/scaffold.js:73:37
    at tryCatcher (/Users/cchen21/WEC/try/mock/node_modules/drydock-scaffold/node_modules/bluebird/js/release/util.js:11:23)
    at Promise._settlePromiseFromHandler (/Users/cchen21/WEC/try/mock/node_modules/drydock-scaffold/node_modules/bluebird/js/release/promise.js:489:31)
    at Promise._settlePromise (/Users/cchen21/WEC/try/mock/node_modules/drydock-scaffold/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromise0 (/Users/cchen21/WEC/try/mock/node_modules/drydock-scaffold/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/Users/cchen21/WEC/try/mock/node_modules/drydock-scaffold/node_modules/bluebird/js/release/promise.js:674:18)
    at Promise._fulfill (/Users/cchen21/WEC/try/mock/node_modules/drydock-scaffold/node_modules/bluebird/js/release/promise.js:615:18)
    at Promise._resolveCallback (/Users/cchen21/WEC/try/mock/node_modules/drydock-scaffold/node_modules/bluebird/js/release/promise.js:416:57)
    at Promise._settlePromiseFromHandler (/Users/cchen21/WEC/try/mock/node_modules/drydock-scaffold/node_modules/bluebird/js/release/promise.js:502:17)
    at Promise._settlePromise (/Users/cchen21/WEC/try/mock/node_modules/drydock-scaffold/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromise0 (/Users/cchen21/WEC/try/mock/node_modules/drydock-scaffold/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/Users/cchen21/WEC/try/mock/node_modules/drydock-scaffold/node_modules/bluebird/js/release/promise.js:674:18)
    at Promise._fulfill (/Users/cchen21/WEC/try/mock/node_modules/drydock-scaffold/node_modules/bluebird/js/release/promise.js:615:18)
    at Promise._resolveCallback (/Users/cchen21/WEC/try/mock/node_modules/drydock-scaffold/node_modules/bluebird/js/release/promise.js:416:57)
    at Promise._settlePromiseFromHandler (/Users/cchen21/WEC/try/mock/node_modules/drydock-scaffold/node_modules/bluebird/js/release/promise.js:502:17)
    at Promise._settlePromise (/Users/cchen21/WEC/try/mock/node_modules/drydock-scaffold/node_modules/bluebird/js/release/promise.js:546:18)
    at Promise._settlePromise0 (/Users/cchen21/WEC/try/mock/node_modules/drydock-scaffold/node_modules/bluebird/js/release/promise.js:591:10)
    at Promise._settlePromises (/Users/cchen21/WEC/try/mock/node_modules/drydock-scaffold/node_modules/bluebird/js/release/promise.js:674:18)
    at Promise._fulfill (/Users/cchen21/WEC/try/mock/node_modules/drydock-scaffold/node_modules/bluebird/js/release/promise.js:615:18)
    at null._onTimeout (/Users/cchen21/WEC/try/mock/node_modules/drydock-scaffold/node_modules/bluebird/js/release/timers.js:32:37)
    at Timer.listOnTimeout (timers.js:92:15)
```

**Comment by divmain** [comment]
@chenchaoyi, are you running Windows?

**Comment by chenchaoyi** [comment]
```
/Users/cchen21/WEC/try/mock/node_modules/drydock-scaffold/lib/write-mocks.js
```

It was Mac OSX.

And it happens when I point my browser to scaffold and goes to `www-e16.walmart.com`.

**Comment by divmain** [comment]
Hmm, I didn't realize OS X had a filename character limit (255 chars).  I suppose we'll have to truncate the filenames.
